### ISSUE TITLE
Consider changing the green (open) color to a traditional color

### ISSUE THREAD

**Issue by jakep** [brickbutton/philips-hue-bathroom-status#1]
**Description**  
Since the light will be green (open) most of the time, I suggest using a color that's more appropriate for an office setting (cooler during the day, warmer at night). The red color is the only indicator necessary to determine whether the bathroom is open or not.

_Pseudo logic_
```
light_color = appropriate_temperature_color(current_time)

if bathroom == "open"
  light_color = "red"
endif
```

**Prototype / Designs**  
N/A

**Latest Assets**  
N/A

**Issue Dependencies**  
N/A

**Comment by blim8183** [comment]
Please clarify.

**Comment by jakep** [comment]
@blim8183 Added pseudo code to help you understand.

**Comment by blim8183** [comment]
But... green means go.

**Comment by jakep** [comment]
@blim8183 Although I agree, that is irrelevant.

**Comment by blim8183** [comment]
I'm sorry. I'm not trying to be difficult. But... I think I need further clarification.

**Comment by blim8183** [comment]
This issue has been resolved.
